Administracion/urls.py
from django.urls import path

from Administracion.views import auth, parametros, veredas, beneficiarios

app_name = 'Administracion'


urlpatterns = [
    path('iniciar-sesion', auth.InicioSesionView.as_view(), name='inicio-sesion'),
    path('cerrar-sesion', auth.CierreSesion.as_view(), name='cierre-sesion'),
    path('obtener-veredas-de-licencias/json', parametros.ObtenerVeredasDeLicencias.as_view(),
         name='obtener-veredas-de-licencias'),
    path('obtener-beneficiarios-de-veredas/json', parametros.ObtenerBeneficiariosDeVeredas.as_view(),
         name='obtener-beneficiarios-de-veredas'),
    path('obtener-veredas-de-municipios/json', parametros.ObtenerVeredaLicenciaDeMunicipio.as_view(),
         name='obtener-veredas-municipios'),

    path('veredas/index', veredas.VeredasView.as_view(), name='veredas-index'),
    path('veredas/crear', veredas.VeredasCrearView.as_view(), name='veredas-crear'),
    path('veredas/<int:id>/editar', veredas.VeredasEditarView.as_view(), name='veredas-editar'),
    path('beneficiarios/index', beneficiarios.BeneficiariosView.as_view(), name='beneficiarios-index'),
    path('beneficiarios/crear', beneficiarios.BeneficiariosCrearView.as_view(), name='beneficiarios-crear'),
    path('beneficiarios/<int:id>/editar', beneficiarios.BeneficiariosEditarView.as_view(), name='beneficiarios-editar'),
]

Proyectos/urls.py
from django.urls import path

from Proyectos.views import views, entregas, facturacion, novedades, graficos

app_name = 'Proyectos'


urlpatterns = [
    path('index', views.ProyectosView.as_view(), name='index'),
    path('crear', views.ProyectosCrearView.as_view(), name='crear'),
    path('<int:id>/editar', views.ProyectosEditarView.as_view(), name='editar'),
    path('entregas-index', entregas.EntregasView.as_view(), name='entregas-index'),
    path('entregas-crear/<int:id>', entregas.EntregasCrearView.as_view(), name='entregas-crear'),
    path('entregas-detalle/<int:id>', entregas.EntregasModalDetalleView.as_view(), name='entregas-detalle'),
    path('facturacion-index', facturacion.FacturacionView.as_view(), name='facturacion-index'),
    path('facturacion-crear/<int:id>', facturacion.FacturacionCrearView.as_view(), name='facturacion-crear'),
    path('facturacion-detalle/<int:id>', facturacion.FacturacionModalDetalleView.as_view(), name='facturacion-detalle'),
    path('novedades-index', novedades.NovedadesView.as_view(), name='novedades-index'),
    path('novedades-crear/<int:id>', novedades.NovedadesCrearView.as_view(), name='novedades-crear'),
    path('novedades-detalle/<int:id>', novedades.NovedadesModalDetalleView.as_view(), name='novedades-detalle'),
    path('graficos-index/<int:id>', graficos.GraficosView.as_view(), name='graficos-index'),
]

SIGPA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from SIGPA.views.index import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('administracion/', include('Administracion.urls', namespace='administracion')),
    path('proyectos/', include('Proyectos.urls', namespace='proyectos')),

] + static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

SIGPA/views/conversiones.py
import json


def convertir_a_json_select(objeto):
    datos = []
    for obj in objeto:
        datos.append({'id': obj.id, 'nombre': obj.nombre})
    return json.dumps(datos)


def convertir_a_json_select_vda_lic(objeto):
    datos = []
    for obj in objeto:
        datos.append({'id': obj.id, 'nombre': obj.vereda.nombre})
    return json.dumps(datos)


def convertir_a_json_select_vda_lic_con_licencia(objeto):
    datos = []
    for obj in objeto:
        datos.append({'id': obj.id, 'nombre': '{0} - ({1})'.format(obj.vereda.nombre, obj.licencia.nombre)})
    return json.dumps(datos)


def convertir_select_vda_lic_con_licencia(objeto):
    datos = []
    for obj in objeto:
        datos.append({'id': obj.id, 'nombre': '{0} - ({1})'.format(obj.vereda.nombre, obj.licencia.nombre)})
    return datos

SIGPA/views/index.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View


class AuthAbsView(View):
    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return super(AuthAbsView, self).dispatch(*args, **kwargs)
        else:
            return redirect(reverse('administracion:inicio-sesion'))


class IndexView(AuthAbsView):
    def get(self, request):
        return render(request, 'SIGPA/index.html')

SIGPA/templates/SIGPA/_base_templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SIGPA</title>
    <!-- Custom fonts for this template-->
    <link href="{% static 'SIGPA/Plantilla/vendor/fontawesome-free/css/all.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'SIGPA/Plantilla/css/css.css' %}" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static 'SIGPA/Plantilla/css/sb-admin-2.min.css'%}" rel="stylesheet">
    <link href="{% static 'SIGPA/css/globales.css'%}" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'SIGPA/Plantilla/img/favicon.ico' %}">
    {% block styles %}
    {% endblock %}
</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
            {% include 'SIGPA/_base_templates/sidebar.html' %}
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    {% include 'SIGPA/_base_templates/topbar.html' %}
                </nav>
                <!-- End of Topbar -->
            </div>
            <!-- End of Main Content -->
            <!-- Begin Page Content -->
            <!-- Notificaciones Toast -->
                {% include 'SIGPA/_base_templates/notificaciones_toast.html' %}
            <!-- End of Footer -->
            <div class="container-fluid">
                {% block main %}

                {% endblock %}
                <div class="modal fade" id="modal-detalle" tabindex="-1" role="dialog" aria-hidden="true"></div>
            </div>
            <!-- End Page Content -->

            <!-- Footer -->
                {% include 'SIGPA/_base_templates/footer.html' %}
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Scroll to Top Button-->

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'SIGPA/Plantilla/vendor/jquery/jquery.js'%}" type="text/javascript"></script>
    <script src="{% static 'SIGPA/Plantilla/vendor/bootstrap/js/bootstrap.bundle.js'%}" type="text/javascript"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'SIGPA/Plantilla/vendor/jquery-easing/jquery.easing.js'%}" type="text/javascript"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'SIGPA/Plantilla/js/sb-admin-2.min.js'%}" type="text/javascript"></script>
    <!-- Page level plugins -->
    <script src="{% static 'SIGPA/Plantilla/vendor/chart.js/Chart.js'%}" type="text/javascript"></script>
    {% if messages %}
        <script>
            $(document).ready(function (){
                $(".toast").toast("show");
            });
        </script>
    {% endif %}

    {% block scripts %}
    {% endblock %}
</body>
</html>

SIGPA/templates/SIGPA/_base_templates/footer.html
<footer class="sticky-footer bg-white" style="position: absolute;
  bottom: 0;
  width: 100%;
  height: 40px;">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; SIGPA v1.0 - Fundación El Alcaraván 2021</span>
        </div>
    </div>
</footer>

SIGPA/templates/SIGPA/_base_templates/notificaciones_toast.html
{% if messages %}
    {% for message in messages %}
        <div class="toast" id="toastBasic" role="alert" aria-live="assertive" aria-atomic="true" data-delay="3000"
             style="position: absolute; top: 80px; right: 1%;" {% if message.tags == 'error' %}data-autohide="false"{% endif %}>
            <div class="toast-header bg- text-white
                    {% if message.tags == 'success' %}
                        bg-primary
                    {% elif message.tags == 'warning' %}
                        bg-warning
                    {% elif message.tags == 'error' %}
                        bg-danger
                    {% endif %}">
                <i data-feather="alert-circle"></i>
                <strong class="mr-auto">
                    {% if message.tags == 'success' %}
                        Trabajo Exitoso!
                    {% elif message.tags == 'warning' %}
                        Advertencia!
                    {% elif message.tags == 'error' %}
                        Error!
                    {% endif %}
                </strong>
                <small class="text-white-50 ml-2 pr-1">Hace 1 segundo</small>
                <a class="fas fa-times-circle text-decoration-none" style="color: #ffffff" href="javascript:$('.toast').toast('hide');" title="Cerrar"></a>
            </div>
            <div class="toast-body">{{ message }}</div>
        </div>
    {% endfor %}
{% endif %}

SIGPA/templates/SIGPA/_base_templates/sidebar.html
{% load static %}
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center" href="/">
        <div class="sidebar-brand-icon">
            <img class="img-profile rounded-circle w-50"
                src="{% static 'SIGPA/Plantilla/img/logo.jpg'%}">
        </div>
        <div class="sidebar-brand-text mx-3">SIGPA</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="/">
            <i class="fas fa-home"></i>
            <span>Inicio</span></a>
    </li>
    <li class="nav-item {% if menu_actual.0 == 'ADM' %}active{% endif %}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseParametrizacion"
            aria-expanded="true" aria-controls="collapseParametrizacion">
            <i class="fas fa-fw fa-cog"></i>
            <span>Administración</span>
        </a>
        <div id="collapseParametrizacion" class="collapse {% if menu_actual.0 == 'ADM' %}show{% endif %}" aria-labelledby="headingParametrizacion" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Parametrización:</h6>
                <a class="collapse-item {% if menu_actual.1 == 'BENEFICIARIOS' %}active{% endif %}" href="{% url 'Administracion:beneficiarios-index' %}">Beneficiarios</a>
                <a class="collapse-item {% if menu_actual.1 == 'VEREDAS' %}active{% endif %}" href="{% url 'Administracion:veredas-index' %}">Veredas</a>
            </div>
        </div>
    </li>
    <li class="nav-item {% if menu_actual.0 == 'GP' %}active{% endif %}">
        <a class="nav-link {% if menu_actual.0 != 'GP' %}collapsed{% endif %}" href="#" data-toggle="collapse" data-target="#collapseGP"
            aria-expanded="true" aria-controls="collapseGP">
            <i class="fab fa-atlassian"></i>
            <span>Gestión de Proyectos</span>
        </a>
        <div id="collapseGP" class="collapse {% if menu_actual.0 == 'GP' %}show{% endif %}" aria-labelledby="headingGP" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Avances:</h6>
                <a class="collapse-item {% if menu_actual.1 == 'ENTREGAS' %}active{% endif %}" href="{% url 'Proyectos:entregas-index' %}">Entregas</a>
                <a class="collapse-item {% if menu_actual.1 == 'FACTURACION' %}active{% endif %}" href="{% url 'Proyectos:facturacion-index' %}">Facturación</a>
                <a class="collapse-item {% if menu_actual.1 == 'NOVEDADES' %}active{% endif %}" href="{% url 'Proyectos:novedades-index' %}">Novedades</a>
            </div>
        </div>
    </li>
    <li class="nav-item {% if menu_actual == 'PROYECTOS' %}active{% endif %}">
        <a class="nav-link" href="{% url 'Proyectos:index' %}">
            <i class="fab fa-atlassian"></i>
            <span>Proyectos</span></a>
    </li>
    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>

SIGPA/templates/SIGPA/_base_templates/topbar.html
{% load static %}

<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
</button>

<!-- Topbar Navbar -->
<ul class="navbar-nav ml-auto">

    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="mr-2 d-none d-lg-inline text-gray-600 small">Usuario</span>
            <img class="img-profile rounded-circle"
                src="{% static 'SIGPA/Plantilla/img/undraw_profile.svg'%}">
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
            aria-labelledby="userDropdown">
            <a class="dropdown-item" href="#">
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                Perfil
            </a>
            <a class="dropdown-item" href="#">
                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                Configuraciones
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'administracion:cierre-sesion' %}">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Cerrar Sesión
            </a>
        </div>
    </li>
</ul>