Administracion/urls.py
from django.urls import path

from Administracion.views import auth, parametros, veredas, beneficiarios

app_name = 'Administracion'


urlpatterns = [
    path('iniciar-sesion', auth.InicioSesionView.as_view(), name='inicio-sesion'),
    path('cerrar-sesion', auth.CierreSesion.as_view(), name='cierre-sesion'),
    path('obtener-veredas-de-licencias/json', parametros.ObtenerVeredasDeLicencias.as_view(),
         name='obtener-veredas-de-licencias'),
    path('obtener-beneficiarios-de-veredas/json', parametros.ObtenerBeneficiariosDeVeredas.as_view(),
         name='obtener-beneficiarios-de-veredas'),
    path('obtener-veredas-de-municipios/json', parametros.ObtenerVeredaLicenciaDeMunicipio.as_view(),
         name='obtener-veredas-municipios'),

    path('veredas/index', veredas.VeredasView.as_view(), name='veredas-index'),
    path('veredas/crear', veredas.VeredasCrearView.as_view(), name='veredas-crear'),
    path('veredas/<int:id>/editar', veredas.VeredasEditarView.as_view(), name='veredas-editar'),
    path('beneficiarios/index', beneficiarios.BeneficiariosView.as_view(), name='beneficiarios-index'),
    path('beneficiarios/crear', beneficiarios.BeneficiariosCrearView.as_view(), name='beneficiarios-crear'),
    path('beneficiarios/<int:id>/editar', beneficiarios.BeneficiariosEditarView.as_view(), name='beneficiarios-editar'),
]

Proyectos/urls.py
from django.urls import path

from Proyectos.views import views, entregas, facturacion, novedades, graficos

app_name = 'Proyectos'


urlpatterns = [
    path('index', views.ProyectosView.as_view(), name='index'),
    path('crear', views.ProyectosCrearView.as_view(), name='crear'),
    path('<int:id>/editar', views.ProyectosEditarView.as_view(), name='editar'),
    path('entregas-index', entregas.EntregasView.as_view(), name='entregas-index'),
    path('entregas-crear/<int:id>', entregas.EntregasCrearView.as_view(), name='entregas-crear'),
    path('entregas-detalle/<int:id>', entregas.EntregasModalDetalleView.as_view(), name='entregas-detalle'),
    path('facturacion-index', facturacion.FacturacionView.as_view(), name='facturacion-index'),
    path('facturacion-crear/<int:id>', facturacion.FacturacionCrearView.as_view(), name='facturacion-crear'),
    path('facturacion-detalle/<int:id>', facturacion.FacturacionModalDetalleView.as_view(), name='facturacion-detalle'),
    path('novedades-index', novedades.NovedadesView.as_view(), name='novedades-index'),
    path('novedades-crear/<int:id>', novedades.NovedadesCrearView.as_view(), name='novedades-crear'),
    path('novedades-detalle/<int:id>', novedades.NovedadesModalDetalleView.as_view(), name='novedades-detalle'),
    path('graficos-index/<int:id>', graficos.GraficosView.as_view(), name='graficos-index'),
]

SIGPA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from SIGPA.views.index import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('administracion/', include('Administracion.urls', namespace='administracion')),
    path('proyectos/', include('Proyectos.urls', namespace='proyectos')),

] + static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

Proyectos/views/entregas.py
import datetime

from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse

from Administracion.models.models import Entregable, VeredaLicencia
from Proyectos.models import ActaEntrega, Proyecto, ProyectoBeneficiario
from Proyectos.models.models import EntregableActaEntrega, ActaEntregaBeneficiario
from SIGPA.views.index import AuthAbsView


class EntregasView(AuthAbsView):
    def get(self, request):
        entregas = ActaEntrega.objects.all()
        return render(request, 'Proyectos/Entregas/index.html',
                      {'entregas': entregas, 'menu_actual': ['GP', 'ENTREGAS']})


class EntregasCrearView(AuthAbsView):
    def get(self, request, id):
        proyecto = Proyecto.objects.get(id=id)
        entregables = Entregable.objects.all()
        beneficiarios = ProyectoBeneficiario.objects.filter(proyecto=proyecto)
        return render(request, 'Proyectos/Entregas/_modal_crear_editar.html',
                      {'proyecto': proyecto, 'beneficiarios': beneficiarios,
                       'entregables': entregables, 'menu_actual': ['GP', 'ENTREGAS']})

    def post(self, request, id):
        entrega = ActaEntrega()
        entrega.proyecto_id = id
        entrega.usuario_crea = request.user
        entrega.responsable = request.POST.get('responsable', '')
        entrega.fecha = request.POST.get('fecha_entrega', '')
        entrega.fecha_crea = datetime.datetime.now()
        entrega.estado = True
        entrega.descripcion = request.POST.get('descripcion', '')
        entrega.archivo = request.FILES.get('acta_entrega', None)

        try:
            entrega.full_clean()
        except Exception as e:
            messages.error(request, 'Se ha generado el error: {0}'.format(e))
            return redirect(reverse('Proyectos:entregas-index'))

        entrega.save()
        entregables = request.POST.getlist('entregable[]', [])
        for ent in entregables:
            EntregableActaEntrega.objects.create(entregable_id=ent, acta_entrega=entrega)

        benefiarios = request.POST.getlist('beneficiario[]', [])
        for ben in benefiarios:
            ActaEntregaBeneficiario.objects.create(beneficiario_id=ben, acta_entrega=entrega)

        messages.success(request, 'Se guardó la entrega correctamente.')
        return redirect(reverse('Proyectos:entregas-index'))


class EntregasModalDetalleView(AuthAbsView):
    def get(self, request, id):
        entrega = ActaEntrega.objects.get(id=id)
        proyectos = VeredaLicencia.objects.all()
        entregas = EntregableActaEntrega.objects.filter(acta_entrega=entrega)
        beneficiarios = ActaEntregaBeneficiario.objects.filter(acta_entrega=entrega)
        return render(request, 'Proyectos/Entregas/_modal_detalle.html',
                      {'entrega': entrega, 'proyectos': proyectos,
                       'beneficiarios': beneficiarios, 'entregas': entregas})

Proyectos/views/facturacion.py
import datetime

from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse

from Proyectos.models import Proyecto
from Proyectos.models.models import Facturacion
from SIGPA.views.index import AuthAbsView


class FacturacionView(AuthAbsView):
    def get(self, request):
        facturacion = Facturacion.objects.all()
        return render(request, 'Proyectos/Facturacion/index.html',
                      {'facturacion': facturacion,  'menu_actual': ['GP', 'FACTURACION']})


class FacturacionCrearView(AuthAbsView):
    def get(self, request, id):
        proyecto = Proyecto.objects.get(id=id)
        return render(request, 'Proyectos/Facturacion/_modal_crear_editar.html',
                      {'proyecto': proyecto, 'menu_actual': ['GP', 'FACTURACION']})

    def post(self, request, id):
        facturacion = Facturacion()
        facturacion.proyecto_id = id
        facturacion.usuario_crea = request.user
        facturacion.codigo_factura = request.POST.get('codigo_factura', '')
        facturacion.valor = request.POST.get('valor', '')
        facturacion.fecha = request.POST.get('fecha_facturacion', '')
        facturacion.fecha_crea = datetime.datetime.now()
        facturacion.estado = True
        try:
            facturacion.full_clean()
        except Exception as e:
            messages.error(request, 'Se ha generado el error: {0}'.format(e))
            return redirect(reverse('Proyectos:facturacion-index'))
        facturacion.save()
        messages.success(request, 'Se guardó la facturación correctamente.')
        return redirect(reverse('Proyectos:facturacion-index'))


class FacturacionModalDetalleView(AuthAbsView):
    def get(self, request, id):
        facturacion = Facturacion.objects.get(id=id)
        return render(request, 'Proyectos/Facturacion/_modal_detalle.html',
                      {'facturacion': facturacion})

Proyectos/views/graficos.py
import json
from datetime import datetime, timedelta

from django.db.models import Sum
from django.shortcuts import render

from Administracion.views.parametros import mes_numero_a_letras, obtener_fecha_fin_de_mes, add_fortnight, add_week
from Proyectos.models import Proyecto, ActaEntrega, Facturacion
from SIGPA.views.index import AuthAbsView

NOW = datetime.now()


class GraficosView(AuthAbsView):
    def get(self, request, id):
        proyecto = Proyecto.objects.get(id=id)
        month_acta_entrega = calculo_mensual(proyecto, ActaEntrega, 'ActaEntrega')
        month_facturacion = calculo_mensual(proyecto, Facturacion, 'Facturacion')

        fortnight_acta_entrega = calculo_quincenal(proyecto, ActaEntrega, 'ActaEntrega')
        fortnight_facturacion = calculo_quincenal(proyecto, Facturacion, 'Facturacion')

        week_acta_entrega = calculo_semanal(proyecto, ActaEntrega, 'ActaEntrega')
        week_facturacion = calculo_semanal(proyecto, Facturacion, 'Facturacion')

        datos = {'mensual': {'acta_entrega': month_acta_entrega, 'facturacion': month_facturacion},
                 'quincenal': {'acta_entrega': fortnight_acta_entrega, 'facturacion': fortnight_facturacion},
                 'semanal': {'acta_entrega': week_acta_entrega, 'facturacion': week_facturacion}}

        return render(request, 'Proyectos/Graficos/index.html',
                      {'proyecto': proyecto, 'datos': datos})


def proceso_calculo(Modelo, proyecto, fecha_1, fecha_2, acumulado, origen):
    consulta = Modelo.objects.filter(proyecto=proyecto, fecha__range=[fecha_1, fecha_2])
    if origen == 'ActaEntrega':
        acumulado = acumulado + consulta.count()
        return {'acumulado': acumulado, 'valor': int((100 * acumulado) / proyecto.n_entregas)}
    elif origen == 'Facturacion':
        valor = consulta.aggregate(Sum('valor'))['valor__sum']
        acumulado = acumulado + valor if valor else 0
        return {'acumulado': acumulado, 'valor': int((100 * acumulado) / proyecto.valor)}


def calculo_mensual(proyecto, Modelo, origen):
    valores = []
    meses = []

    fecha_1 = proyecto.fecha_inicio
    fecha_2 = obtener_fecha_fin_de_mes(fecha_1.year, fecha_1.month)
    acumulado = 0
    while fecha_2.month <= int(NOW.strftime("%m")) and fecha_2.year <= int(NOW.strftime("%Y")):
        meses.append(mes_numero_a_letras(fecha_2.month))
        datos = proceso_calculo(Modelo, proyecto, fecha_1, fecha_2, acumulado, origen)
        acumulado = datos['acumulado']
        valores.append(datos['valor'])
        fecha_1 = fecha_2 + timedelta(days=1)
        fecha_2 = obtener_fecha_fin_de_mes(fecha_1.year, fecha_1.month)
    return {'meses': json.dumps(meses), 'valores': valores}


def calculo_quincenal(proyecto, Modelo, origen):
    valores = []
    quincenas = []

    fecha_1 = proyecto.fecha_inicio
    fecha_2 = add_fortnight(fecha_1, 1)
    acumulado = 0
    contador = 0
    while fecha_2.month <= int(NOW.strftime("%m")) and fecha_2.year <= int(NOW.strftime("%Y")):
        contador += 1
        quincenas.append("Quinc {0}".format(contador))
        datos = proceso_calculo(Modelo, proyecto, fecha_1, fecha_2, acumulado, origen)
        acumulado = datos['acumulado']
        valores.append(datos['valor'])
        fecha_1 = fecha_2 + timedelta(days=1)
        fecha_2 = add_fortnight(fecha_1, 1)
    return {'quincenas': json.dumps(quincenas), 'valores': valores}


def calculo_semanal(proyecto, Modelo, origen):
    valores = []
    semanas = []

    fecha_1 = proyecto.fecha_inicio
    fecha_2 = add_week(fecha_1, 1)
    acumulado = 0
    contador = 0
    while fecha_2.month <= int(NOW.strftime("%m")) and fecha_2.year <= int(NOW.strftime("%Y")):
        contador += 1
        semanas.append("Sem {0}".format(contador))
        datos = proceso_calculo(Modelo, proyecto, fecha_1, fecha_2, acumulado, origen)
        acumulado = datos['acumulado']
        valores.append(datos['valor'])
        fecha_1 = fecha_2 + timedelta(days=1)
        fecha_2 = add_week(fecha_1, 1)
    return {'semanas': json.dumps(semanas), 'valores': valores}

Proyectos/views/novedades.py
import datetime

from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse

from Administracion.models.models import TipoNovedad
from Proyectos.models import Proyecto, ProyectoBeneficiario
from Proyectos.models.models import ProyectoNovedad, ProyectoNovedadBeneficiario
from SIGPA.views.index import AuthAbsView


class NovedadesView(AuthAbsView):
    def get(self, request):
        novedades = ProyectoNovedad.objects.all()
        return render(request, 'Proyectos/Novedades/index.html',
                      {'novedades': novedades, 'menu_actual': ['GP', 'NOVEDADES']})


class NovedadesCrearView(AuthAbsView):
    def get(self, request, id):
        proyecto = Proyecto.objects.get(id=id)
        tipos_novedades = TipoNovedad.objects.all()
        porcentajes = [{'id': 10, 'nombre': '10%'}, {'id': 20, 'nombre': '20%'}, {'id': 30, 'nombre': '30%'},
                       {'id': 50, 'nombre': '50%'}]
        beneficiarios = ProyectoBeneficiario.objects.filter(proyecto=proyecto)
        return render(request, 'Proyectos/Novedades/_modal_crear_editar.html',
                      {'proyecto': proyecto, 'beneficiarios': beneficiarios, 'porcentajes': porcentajes,
                       'tipos_novedades': tipos_novedades})

    def post(self, request, id):
        novedad = ProyectoNovedad()
        novedad.proyecto_id = id
        novedad.usuario_crea = request.user
        novedad.tipo_novedad_id = request.POST.get('tipo_novedad', '')
        novedad.responsable = request.POST.get('responsable', '')
        novedad.porcentaje = request.POST.get('porcentaje', '')
        novedad.fecha = request.POST.get('fecha_novedad', '')
        novedad.descripcion = request.POST.get('descripcion', '')
        novedad.fecha_crea = datetime.datetime.now()
        novedad.estado = True

        try:
            novedad.full_clean()
        except Exception as e:
            messages.error(request, 'Se ha generado el error: {0}'.format(e))
            return redirect(reverse('Proyectos:novedades-index'))

        novedad.save()

        benefiarios = request.POST.getlist('beneficiario[]', [])
        for ben in benefiarios:
            ProyectoNovedadBeneficiario.objects.create(beneficiario_id=ben, proyecto_novedad=novedad)

        messages.success(request, 'Se guardó la novedad correctamente.')
        return redirect(reverse('Proyectos:novedades-index'))


class NovedadesModalDetalleView(AuthAbsView):
    def get(self, request, id):
        novedad = ProyectoNovedad.objects.get(id=id)
        beneficiarios = ProyectoNovedadBeneficiario.objects.filter(proyecto_novedad=novedad)
        return render(request, 'Proyectos/Novedades/_modal_detalle.html',
                      {'novedad': novedad, 'beneficiarios': beneficiarios, })

Proyectos/templates/Proyectos/index.html
{% extends 'SIGPA/_base_templates/base.html' %}
{% load static %}
{% load humanize %}
{% block styles %}
    <link href="{% static 'SIGPA/DataTable/jquery.dataTables.min.css' %}" rel="stylesheet">
    <link href="{% static 'SIGPA/DataTable/responsive.dataTables.min.css' %}" rel="stylesheet">
{% endblock %}
{% block main %}
 <h1 class="h3 mb-2 text-gray-800">Proyectos</h1>
                <p class="mb-4">Relacion de los proyectos ejecutados por la Fundación el Alcaraván</p>
    <div class="card shadow mb-5">
    <div class="card-header py-3">
        <a class="fas fa-2x fa-plus-circle text-decoration-none" id="crear" href="{% url 'Proyectos:crear' %}" title="Crear"></a>
    </div>
        <div class="card-body">
            <table class="table table-bordered display nowrap w-100" id="dataTable">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Nombre</th>
                        <th>Director</th>
                        <th>Descripción</th>
                        <th>Constitución</th>
                        <th>Valor</th>
                        <th>Inicia</th>
                        <th>Finaliza</th>
                        <th>Creado</th>
                        <th>Estado</th>
                        <th>Fuente de Recursos</th>
                        <th>#. Entregas</th>
                        <th>Centro de Costos</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pro in proyectos %}
                    <tr>
                        <th>{{ pro.codigo_proyecto }}</th>
                        <th>{{ pro.nombre }}</th>
                        <th>{{ pro.director }}</th>
                        <th>{{ pro.descripcion }}</th>
                        <th>{{ pro.fecha_constitucion|date:'d-m-Y' }}</th>
                        <th>$ {{ pro.valor|intcomma:False }}</th>
                        <th>{{ pro.fecha_inicio|date:'d-m-Y' }}</th>
                        <th>{{ pro.fecha_final|date:'d-m-Y' }}</th>
                        <th>{{ pro.fecha_crea|date:'d-m-Y' }}</th>
                        <th>{{ pro.estado }}</th>
                        <th>{{ pro.fuente_recursos }}</th>
                        <th>{{ pro.n_entregas }}</th>
                        <th>{{ pro.centro_costos }}</th>
                        <th class="text-align-center">
                            <a class="fas fa-edit text-decoration-none" id="editar" href="{% url 'Proyectos:editar' pro.id %}" title="Editar"></a>
                            <a class="fas fa-clipboard-check text-decoration-none" id="entrega" href="javascript:gestionarModal('{% url 'proyectos:entregas-crear' pro.id %}', 'modal-entrega')" title="Agregar Entrega"></a>
                            <a class="fas fa-file-invoice-dollar text-decoration-none" id="facturacion" href="javascript:gestionarModal('{% url 'proyectos:facturacion-crear' pro.id %}', 'modal-facturacion')" title="Agregar Facturación"></a>
                            <a class="fas fa-newspaper text-decoration-none" id="novedad" href="javascript:gestionarModal('{% url 'proyectos:novedades-crear' pro.id %}', 'modal-novedad')" title="Agregar Novedad"></a>
                            <a class="fas fa-chart-line text-decoration-none" id="grafico" href="javascript:gestionarModal('{% url 'proyectos:graficos-index' pro.id %}', 'modal-grafico')" title="Estadisticas"></a>
                        </th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal fade" id="modal-entrega" tabindex="-1" role="dialog" aria-hidden="true"></div>
    <div class="modal fade" id="modal-facturacion" tabindex="-1" role="dialog" aria-hidden="true"></div>
    <div class="modal fade" id="modal-novedad" tabindex="-1" role="dialog" aria-hidden="true"></div>
    <div class="modal fade" id="modal-grafico" tabindex="-1" role="dialog" aria-hidden="true"></div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'SIGPA/DataTable/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'SIGPA/DataTable/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'SIGPA/DataTable/modificacionesDataTable.js' %}"></script>
    <script src="{% static 'Administracion/gestionModal.js' %}"></script>
    <script>
        let tabla = $('#dataTable');
        tabla.dataTable({
            responsive: true,
            lengthChange: false,
            bPaginate: true,
            aaSorting: [[0, 'asc']],

            columnDefs: [
                { responsivePriority: 1, targets: 0 },
                { responsivePriority: 2, targets: 1 },
                { responsivePriority: 2, targets: 2 },
                { responsivePriority: 3, targets: 5 },
                { responsivePriority: 4, targets: 6 },
                { responsivePriority: 5, targets: 7 },
                { responsivePriority: 6, targets: 10 },
                { responsivePriority: 1, targets: 13 },
            ],
            language: idiomaTabla
        });
        tabla.find("input").attr("placeholder", "Buscar");
    </script>
{% endblock %}