Administracion/urls.py
from django.urls import path

from Administracion.views import auth, parametros, veredas, beneficiarios

app_name = 'Administracion'


urlpatterns = [
    path('iniciar-sesion', auth.InicioSesionView.as_view(), name='inicio-sesion'),
    path('cerrar-sesion', auth.CierreSesion.as_view(), name='cierre-sesion'),
    path('obtener-veredas-de-licencias/json', parametros.ObtenerVeredasDeLicencias.as_view(),
         name='obtener-veredas-de-licencias'),
    path('obtener-beneficiarios-de-veredas/json', parametros.ObtenerBeneficiariosDeVeredas.as_view(),
         name='obtener-beneficiarios-de-veredas'),
    path('obtener-veredas-de-municipios/json', parametros.ObtenerVeredaLicenciaDeMunicipio.as_view(),
         name='obtener-veredas-municipios'),

    path('veredas/index', veredas.VeredasView.as_view(), name='veredas-index'),
    path('veredas/crear', veredas.VeredasCrearView.as_view(), name='veredas-crear'),
    path('veredas/<int:id>/editar', veredas.VeredasEditarView.as_view(), name='veredas-editar'),
    path('beneficiarios/index', beneficiarios.BeneficiariosView.as_view(), name='beneficiarios-index'),
    path('beneficiarios/crear', beneficiarios.BeneficiariosCrearView.as_view(), name='beneficiarios-crear'),
    path('beneficiarios/<int:id>/editar', beneficiarios.BeneficiariosEditarView.as_view(), name='beneficiarios-editar'),
]

SIGPA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from SIGPA.views.index import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('administracion/', include('Administracion.urls', namespace='administracion')),
    path('proyectos/', include('Proyectos.urls', namespace='proyectos')),

] + static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

Administracion/views/beneficiarios.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse

from Administracion.models import VeredaLicencia, Municipio, Beneficiario, TipoBeneficiario
from SIGPA.views.conversiones import convertir_select_vda_lic_con_licencia
from SIGPA.views.index import AuthAbsView


class BeneficiariosView(AuthAbsView):
    def get(self, request):
        beneficiarios = Beneficiario.objects.all()
        return render(request, 'Administracion/Beneficiarios/index.html',
                      {'beneficiarios': beneficiarios, 'menu_actual': ['ADM', 'BENEFICIARIOS']})


class BeneficiariosCrearView(AuthAbsView):
    def get(self, request):
        tipos_beneficiarios = TipoBeneficiario.objects.all()
        municipios = Municipio.objects.all()
        return render(request, 'Administracion/Beneficiarios/_modal_crear_editar.html',
                      {'tipos_beneficiarios': tipos_beneficiarios, 'municipios': municipios, 'origen': 'CREAR',
                       'menu_actual': ['ADM', 'BENEFICIARIOS']})

    def post(self, request):
        beneficiario = Beneficiario.data_form(request)
        try:
            beneficiario.save()
        except Exception as e:
            messages.error(request, 'Se ha generado el error: {0}'.format(e))
            return redirect(reverse('Administracion:beneficiarios-index'))

        messages.success(request, 'Se creó el beneficiario correctamente.')
        return redirect(reverse('Administracion:beneficiarios-index'))


class BeneficiariosEditarView(AuthAbsView):
    def get(self, request, id):
        beneficiario = Beneficiario.objects.get(id=id)
        tipos_beneficiarios = TipoBeneficiario.objects.all()
        municipios = Municipio.objects.all()
        veredas = convertir_select_vda_lic_con_licencia(VeredaLicencia
                                                        .objects.filter(vereda__municipio=beneficiario.
                                                                        vereda_licencia.vereda.municipio))
        return render(request, 'Administracion/Beneficiarios/_modal_crear_editar.html',
                      {'beneficiario': beneficiario, 'tipos_beneficiarios': tipos_beneficiarios,
                       'municipios': municipios, 'veredas': veredas, 'origen': 'EDITAR',
                       'menu_actual': ['ADM', 'BENEFICIARIOS']})

    def post(self, request, id):
        beneficiario = Beneficiario.data_form(request)
        beneficiario.id = id
        try:
            beneficiario.save(update_fields=['nombre', 'vereda_licencia', 'tipo_beneficiario',
                                             'numero_personas', 'estado'])
        except Exception as e:
            messages.error(request, 'Se ha generado el error: {0}'.format(e))
            return redirect(reverse('Administracion:beneficiarios-index'))

        messages.success(request, 'Se guardó el beneficiario correctamente.')
        return redirect(reverse('Administracion:beneficiarios-index'))

Administracion/views/parametros.py
import calendar
from datetime import datetime, timedelta

from django.http import JsonResponse

from Administracion.models import VeredaLicencia, Beneficiario
from SIGPA.views.conversiones import convertir_a_json_select, convertir_a_json_select_vda_lic, \
    convertir_a_json_select_vda_lic_con_licencia
from SIGPA.views.index import AuthAbsView


class ObtenerVeredasDeLicencias(AuthAbsView):
    def get(self, request):
        sel_list = obtener_datos_get_ajax(request)
        try:
            veredas = convertir_a_json_select_vda_lic(VeredaLicencia.objects.filter(licencia_id__in=sel_list))
            return JsonResponse(veredas, safe=False)
        except:
            return JsonResponse({"Error": "True"})


class ObtenerBeneficiariosDeVeredas(AuthAbsView):
    def get(self, request):
        sel_list = obtener_datos_get_ajax(request)
        try:
            beneficiarios = convertir_a_json_select(Beneficiario.objects.filter(vereda_id__in=sel_list))
            return JsonResponse(beneficiarios, safe=False)
        except:
            return JsonResponse({"Error": "True"})


class ObtenerVeredaLicenciaDeMunicipio(AuthAbsView):
    def get(self, request):
        sel_list = obtener_datos_get_ajax(request)
        try:
            veredas = convertir_a_json_select_vda_lic_con_licencia(VeredaLicencia.objects
                                                                   .filter(vereda__municipio__in=sel_list))
            return JsonResponse(veredas, safe=False)
        except:
            return JsonResponse({"Error": "True"})


def obtener_datos_get_ajax(request):
    selecciones = request.GET.get('selecciones')
    sel_list = []
    if len(selecciones) > 0:
        sel_list = selecciones.split(',')
    return sel_list


def add_months(d, meses):
    mes_nuevo = (meses + d.month) % 12
    anio_nuevo = d.year + (meses + d.month) // 12
    if mes_nuevo == 0:
        mes_nuevo = 12
        anio_nuevo -= 1
    dias_mes_nuevo = calendar.monthrange(anio_nuevo, mes_nuevo)[1]
    dias_nuevo = d.day if dias_mes_nuevo > d.day else dias_mes_nuevo
    return d.replace(year=anio_nuevo, month=mes_nuevo, day=dias_nuevo)


def add_fortnight(d, quincenas):
    return d + timedelta(days=(15*quincenas))


def add_week(d, semanas):
    return d + timedelta(days=(7*semanas))


def fijar_fecha_inicio_mes(fecha):
    return fecha.replace(fecha.year, fecha.month, 1)


def obtener_fecha_fin_de_mes(anho, mes):
    return datetime.strptime('{0}-{1}-{2}'.format(anho, mes, (calendar.monthrange(anho, mes))[1]), "%Y-%m-%d")


def mes_numero_a_letras(mes) -> str:
    if mes == 1:
        return "Ene"
    elif mes == 2:
        return "Feb"
    elif mes == 3:
        return "Mar"
    elif mes == 4:
        return "Abr"
    elif mes == 5:
        return "May"
    elif mes == 6:
        return "Jun"
    elif mes == 7:
        return "Jul"
    elif mes == 8:
        return "Ago"
    elif mes == 9:
        return "Sep"
    elif mes == 10:
        return "Oct"
    elif mes == 11:
        return "Nov"
    elif mes == 12:
        return "Dic"

Administracion/views/veredas.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse

from Administracion.models import VeredaLicencia, Licencia, Municipio, Vereda
from SIGPA.views.index import AuthAbsView


class VeredasView(AuthAbsView):
    def get(self, request):
        veredas = VeredaLicencia.objects.all()
        return render(request, 'Administracion/Veredas/index.html',
                      {'veredas': veredas, 'menu_actual': ['ADM', 'VEREDAS']})


class VeredasCrearView(AuthAbsView):
    def get(self, request):
        licencias = Licencia.objects.all()
        municipios = Municipio.objects.all()
        return render(request, 'Administracion/Veredas/_modal_crear_editar.html',
                      {'licencias': licencias, 'municipios': municipios, 'origen': 'CREAR',
                       'menu_actual': ['ADM', 'VEREDAS']})

    def post(self, request):
        vereda = Vereda()
        vereda.nombre = request.POST.get('nombre', '')
        vereda.municipio_id = request.POST.get('municipio', '')
        vereda.estado = True
        vereda_licencia = VeredaLicencia()
        vereda_licencia.vereda = vereda
        vereda_licencia.licencia_id = request.POST.get('licencia', '')

        try:
            vereda.save()
        except Exception as e:
            messages.error(request, 'Se ha generado el error: {0}'.format(e))

        try:
            vereda_licencia.save()
        except Exception as e:
            messages.error(request, 'Se ha generado el error: {0}'.format(e))

        messages.success(request, 'Se creó la vereda correctamente.')
        return redirect(reverse('Administracion:veredas-index'))


class VeredasEditarView(AuthAbsView):
    def get(self, request, id):
        vereda_licencia = VeredaLicencia.objects.get(id=id)
        licencias = Licencia.objects.all()
        municipios = Municipio.objects.all()
        return render(request, 'Administracion/Veredas/_modal_crear_editar.html',
                      {'vereda_licencia': vereda_licencia, 'licencias': licencias,
                       'municipios': municipios, 'origen': 'EDITAR', 'menu_actual': ['ADM', 'VEREDAS']})

    def post(self, request, id):
        vereda_licencia = VeredaLicencia.objects.get(id=id)
        vereda_licencia.licencia_id = request.POST.get('licencia', '')
        vereda = Vereda.objects.get(id=vereda_licencia.vereda_id)
        vereda.nombre = request.POST.get('nombre', '')
        vereda.municipio_id = request.POST.get('municipio', '')
        vereda.estado = request.POST.get('estado', 'False') == 'on'

        try:
            vereda_licencia.save(update_fields=['licencia_id'])
        except Exception as e:
            messages.error(request, 'Se ha generado el error: {0}'.format(e))

        try:
            vereda.save(update_fields=['nombre', 'municipio_id', 'estado'])
        except Exception as e:
            messages.error(request, 'Se ha generado el error: {0}'.format(e))

        messages.success(request, 'Se guardó la vereda correctamente.')
        return redirect(reverse('Administracion:veredas-index'))

Administracion/templates/Administracion/Beneficiarios/_modal_crear_editar.html
{% if origen == 'CREAR' %}
    <form action="{% url 'administracion:beneficiarios-crear' %}" id="frm-beneficiario" method="post" enctype="multipart/form-data">
{% else %}
    <form action="{% url 'administracion:beneficiarios-editar' beneficiario.id %}" id="frm-beneficiario" method="post" enctype="multipart/form-data">
{% endif %}
{% csrf_token %}
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{% if origen == 'CREAR' %}Crear Beneficiario{% else %}Modificar Beneficiario{% endif %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group row">
                    <div class="col-xs-12 col-sm-12 mb-12">
                        <label for="nombre_id" id="label_nombre_id">Nombre</label>
                        <input type="text" class="form-control form-control-md" id="nombre_id" name="nombre"
                               placeholder="Nombre" maxlength="100" value="{{ beneficiario.nombre }}" required>
                    </div>
                    <div class="col-xs-12 col-sm-6 mb-6">
                        <label for="select_municipio_id" id="label_municipio_id">Municipio</label>
                        <select class="form-control form-control-md select2" id="select_municipio_id" name="municipio" required>
                            <option value="">Seleccione una opción</option>
                            {% for mun in municipios %}
                                <option value="{{ mun.id }}" {% if beneficiario.vereda_licencia.vereda.municipio == mun %} selected {% endif %}>{{ mun.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-xs-12 col-sm-6 mb-6">
                        <label for="select_vereda_id" id="label_vereda_id">Vereda (Licencia)</label>
                        <select class="form-control form-control-md select2" id="select_vereda_id" name="vereda" required>
                            <option value="">Seleccione una opción</option>
                            {% for ver in veredas %}
                                <option value="{{ ver.id }}" {% if beneficiario.vereda_licencia_id == ver.id %} selected {% endif %}>{{ ver.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-xs-12 col-sm-6 mb-6">
                        <label for="select_tipo_beneficiario_id" id="label_tipo_beneficiario_id">Tipo de Beneficiario</label>
                        <select class="form-control form-control-md select2" id="tipo_beneficiario_id" name="tipo_beneficiario" required>
                            <option value="">Seleccione una opción</option>
                            {% for tb in tipos_beneficiarios %}
                                <option value="{{ tb.id }}" {% if beneficiario.tipo_beneficiario == tb %} selected {% endif %}>{{ tb.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-xs-12 col-sm-6 mb-6">
                        <label for="numero_personas_id" id="label_numero_personas_id"># Personas</label>
                        <input type="number" class="form-control form-control-md" id="numero_personas_id" name="numero_personas"
                               placeholder="Número de Personas" maxlength="100" value="{{ beneficiario.numero_personas }}" required>
                    </div>
                    {% if origen == 'EDITAR' %}
                    <div class="col-xs-12 col-sm-12 mb-12 pt-2">
                        <div class="custom-control custom-switch">
                          <input type="checkbox" class="form-control form-control-md custom-control-input non-selectable" {% if beneficiario.estado %} checked {% endif %} id="customSwitches" name="estado">
                          <label class="custom-control-label" for="customSwitches">Estado</label>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">
                    {% if origen == 'CREAR' %}Crear{% else %}Guardar{% endif %}
                </button>
            </div>
        </div>
    </div>
</form>
<script>
        $(document).ready(function () {
            $('#select_municipio_id').change(function() {
                cargarDatosSelect($('#select_municipio_id'), $('#select_vereda_id'),
                    "{% url 'administracion:obtener-veredas-municipios' %}");
            });
        });
</script>

Administracion/templates/Administracion/Beneficiarios/index.html
{% extends 'SIGPA/_base_templates/base.html' %}
{% load static %}
{% load humanize %}
{% block styles %}
    <link href="{% static 'SIGPA/DataTable/jquery.dataTables.min.css' %}" rel="stylesheet">
    <link href="{% static 'SIGPA/DataTable/responsive.dataTables.min.css' %}" rel="stylesheet">
{% endblock %}
{% block main %}
 <h1 class="h3 mb-2 text-gray-800">Beneficiarios</h1>
                <p class="mb-4">Relacion de los beneficiarios de los proyectos de la Fundación</p>
    <div class="card shadow mb-5">
    <div class="card-header py-3">
        <a class="fas fa-2x fa-plus-circle text-decoration-none" id="crear" href="javascript:gestionarModal('{% url 'administracion:beneficiarios-crear' %}', 'modal-beneficiario')" title="Crear"></a>
    </div>
        <div class="card-body">
            <table class="table table-bordered display nowrap w-100" id="dataTable">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Número de Personas</th>
                        <th>Tipo de Beneficiario</th>
                        <th>Vereda</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ben in beneficiarios %}
                    <tr>
                        <th>{{ ben.nombre }}</th>
                        <th>{{ ben.numero_personas }}</th>
                        <th>{{ ben.tipo_beneficiario }}</th>
                        <th>{{ ben.vereda_licencia }}</th>
                        <th>{% if ben.estado %}
                                <i class="fas fa-2x fa-check-circle"></i>
                            {% else %}
                                <i class="fas fa-2x fa-times-circle"></i>
                            {% endif %}
                        </th>
                        <th class="text-align-center">
                            <a class="fas fa-2x fa-edit text-decoration-none" id="editar" href="javascript:gestionarModal('{% url 'administracion:beneficiarios-editar' ben.id %}', 'modal-beneficiario')" title="Editar"></a>
                        </th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal fade" id="modal-beneficiario" tabindex="-1" role="dialog" aria-hidden="true"></div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'SIGPA/DataTable/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'SIGPA/DataTable/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'SIGPA/DataTable/modificacionesDataTable.js' %}"></script>
    <script src="{% static 'Administracion/gestionModal.js' %}"></script>
    <script src="{% static 'SIGPA/Plantilla/plugins/select2/js/select2.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'SIGPA/Plantilla/custom/modificacionesSelect2.js' %}" type="text/javascript"></script>
    <script src="{% static 'SIGPA/Plantilla/custom/selectDependiente.js' %}" type="text/javascript"></script>
    <script>
        let tabla = $('#dataTable');
        tabla.dataTable({
            responsive: true,
            lengthChange: false,
            bPaginate: true,
            aaSorting: [[0, 'asc']],

            columnDefs: [
                { responsivePriority: 1, targets: 0 },
                { responsivePriority: 2, targets: 5 },
            ],
            language: idiomaTabla
        });
        tabla.find("input").attr("placeholder", "Buscar");
    </script>
{% endblock %}