Proyectos/urls.py
from django.urls import path

from Proyectos.views import views, entregas, facturacion, novedades, graficos

app_name = 'Proyectos'


urlpatterns = [
    path('index', views.ProyectosView.as_view(), name='index'),
    path('crear', views.ProyectosCrearView.as_view(), name='crear'),
    path('<int:id>/editar', views.ProyectosEditarView.as_view(), name='editar'),
    path('entregas-index', entregas.EntregasView.as_view(), name='entregas-index'),
    path('entregas-crear/<int:id>', entregas.EntregasCrearView.as_view(), name='entregas-crear'),
    path('entregas-detalle/<int:id>', entregas.EntregasModalDetalleView.as_view(), name='entregas-detalle'),
    path('facturacion-index', facturacion.FacturacionView.as_view(), name='facturacion-index'),
    path('facturacion-crear/<int:id>', facturacion.FacturacionCrearView.as_view(), name='facturacion-crear'),
    path('facturacion-detalle/<int:id>', facturacion.FacturacionModalDetalleView.as_view(), name='facturacion-detalle'),
    path('novedades-index', novedades.NovedadesView.as_view(), name='novedades-index'),
    path('novedades-crear/<int:id>', novedades.NovedadesCrearView.as_view(), name='novedades-crear'),
    path('novedades-detalle/<int:id>', novedades.NovedadesModalDetalleView.as_view(), name='novedades-detalle'),
    path('graficos-index/<int:id>', graficos.GraficosView.as_view(), name='graficos-index'),
]

SIGPA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from SIGPA.views.index import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('administracion/', include('Administracion.urls', namespace='administracion')),
    path('proyectos/', include('Proyectos.urls', namespace='proyectos')),

] + static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

Proyectos/views/entregas.py
import datetime

from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse

from Administracion.models.models import Entregable, VeredaLicencia
from Proyectos.models import ActaEntrega, Proyecto, ProyectoBeneficiario
from Proyectos.models.models import EntregableActaEntrega, ActaEntregaBeneficiario
from SIGPA.views.index import AuthAbsView


class EntregasView(AuthAbsView):
    def get(self, request):
        entregas = ActaEntrega.objects.all()
        return render(request, 'Proyectos/Entregas/index.html',
                      {'entregas': entregas, 'menu_actual': ['GP', 'ENTREGAS']})


class EntregasCrearView(AuthAbsView):
    def get(self, request, id):
        proyecto = Proyecto.objects.get(id=id)
        entregables = Entregable.objects.all()
        beneficiarios = ProyectoBeneficiario.objects.filter(proyecto=proyecto)
        return render(request, 'Proyectos/Entregas/_modal_crear_editar.html',
                      {'proyecto': proyecto, 'beneficiarios': beneficiarios,
                       'entregables': entregables, 'menu_actual': ['GP', 'ENTREGAS']})

    def post(self, request, id):
        entrega = ActaEntrega()
        entrega.proyecto_id = id
        entrega.usuario_crea = request.user
        entrega.responsable = request.POST.get('responsable', '')
        entrega.fecha = request.POST.get('fecha_entrega', '')
        entrega.fecha_crea = datetime.datetime.now()
        entrega.estado = True
        entrega.descripcion = request.POST.get('descripcion', '')
        entrega.archivo = request.FILES.get('acta_entrega', None)

        try:
            entrega.full_clean()
        except Exception as e:
            messages.error(request, 'Se ha generado el error: {0}'.format(e))
            return redirect(reverse('Proyectos:entregas-index'))

        entrega.save()
        entregables = request.POST.getlist('entregable[]', [])
        for ent in entregables:
            EntregableActaEntrega.objects.create(entregable_id=ent, acta_entrega=entrega)

        benefiarios = request.POST.getlist('beneficiario[]', [])
        for ben in benefiarios:
            ActaEntregaBeneficiario.objects.create(beneficiario_id=ben, acta_entrega=entrega)

        messages.success(request, 'Se guardó la entrega correctamente.')
        return redirect(reverse('Proyectos:entregas-index'))


class EntregasModalDetalleView(AuthAbsView):
    def get(self, request, id):
        entrega = ActaEntrega.objects.get(id=id)
        proyectos = VeredaLicencia.objects.all()
        entregas = EntregableActaEntrega.objects.filter(acta_entrega=entrega)
        beneficiarios = ActaEntregaBeneficiario.objects.filter(acta_entrega=entrega)
        return render(request, 'Proyectos/Entregas/_modal_detalle.html',
                      {'entrega': entrega, 'proyectos': proyectos,
                       'beneficiarios': beneficiarios, 'entregas': entregas})

Proyectos/views/facturacion.py
import datetime

from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse

from Proyectos.models import Proyecto
from Proyectos.models.models import Facturacion
from SIGPA.views.index import AuthAbsView


class FacturacionView(AuthAbsView):
    def get(self, request):
        facturacion = Facturacion.objects.all()
        return render(request, 'Proyectos/Facturacion/index.html',
                      {'facturacion': facturacion,  'menu_actual': ['GP', 'FACTURACION']})


class FacturacionCrearView(AuthAbsView):
    def get(self, request, id):
        proyecto = Proyecto.objects.get(id=id)
        return render(request, 'Proyectos/Facturacion/_modal_crear_editar.html',
                      {'proyecto': proyecto, 'menu_actual': ['GP', 'FACTURACION']})

    def post(self, request, id):
        facturacion = Facturacion()
        facturacion.proyecto_id = id
        facturacion.usuario_crea = request.user
        facturacion.codigo_factura = request.POST.get('codigo_factura', '')
        facturacion.valor = request.POST.get('valor', '')
        facturacion.fecha = request.POST.get('fecha_facturacion', '')
        facturacion.fecha_crea = datetime.datetime.now()
        facturacion.estado = True
        try:
            facturacion.full_clean()
        except Exception as e:
            messages.error(request, 'Se ha generado el error: {0}'.format(e))
            return redirect(reverse('Proyectos:facturacion-index'))
        facturacion.save()
        messages.success(request, 'Se guardó la facturación correctamente.')
        return redirect(reverse('Proyectos:facturacion-index'))


class FacturacionModalDetalleView(AuthAbsView):
    def get(self, request, id):
        facturacion = Facturacion.objects.get(id=id)
        return render(request, 'Proyectos/Facturacion/_modal_detalle.html',
                      {'facturacion': facturacion})

Proyectos/views/graficos.py
import json
from datetime import datetime, timedelta

from django.db.models import Sum
from django.shortcuts import render

from Administracion.views.parametros import mes_numero_a_letras, obtener_fecha_fin_de_mes, add_fortnight, add_week
from Proyectos.models import Proyecto, ActaEntrega, Facturacion
from SIGPA.views.index import AuthAbsView

NOW = datetime.now()


class GraficosView(AuthAbsView):
    def get(self, request, id):
        proyecto = Proyecto.objects.get(id=id)
        month_acta_entrega = calculo_mensual(proyecto, ActaEntrega, 'ActaEntrega')
        month_facturacion = calculo_mensual(proyecto, Facturacion, 'Facturacion')

        fortnight_acta_entrega = calculo_quincenal(proyecto, ActaEntrega, 'ActaEntrega')
        fortnight_facturacion = calculo_quincenal(proyecto, Facturacion, 'Facturacion')

        week_acta_entrega = calculo_semanal(proyecto, ActaEntrega, 'ActaEntrega')
        week_facturacion = calculo_semanal(proyecto, Facturacion, 'Facturacion')

        datos = {'mensual': {'acta_entrega': month_acta_entrega, 'facturacion': month_facturacion},
                 'quincenal': {'acta_entrega': fortnight_acta_entrega, 'facturacion': fortnight_facturacion},
                 'semanal': {'acta_entrega': week_acta_entrega, 'facturacion': week_facturacion}}

        return render(request, 'Proyectos/Graficos/index.html',
                      {'proyecto': proyecto, 'datos': datos})


def proceso_calculo(Modelo, proyecto, fecha_1, fecha_2, acumulado, origen):
    consulta = Modelo.objects.filter(proyecto=proyecto, fecha__range=[fecha_1, fecha_2])
    if origen == 'ActaEntrega':
        acumulado = acumulado + consulta.count()
        return {'acumulado': acumulado, 'valor': int((100 * acumulado) / proyecto.n_entregas)}
    elif origen == 'Facturacion':
        valor = consulta.aggregate(Sum('valor'))['valor__sum']
        acumulado = acumulado + valor if valor else 0
        return {'acumulado': acumulado, 'valor': int((100 * acumulado) / proyecto.valor)}


def calculo_mensual(proyecto, Modelo, origen):
    valores = []
    meses = []

    fecha_1 = proyecto.fecha_inicio
    fecha_2 = obtener_fecha_fin_de_mes(fecha_1.year, fecha_1.month)
    acumulado = 0
    while fecha_2.month <= int(NOW.strftime("%m")) and fecha_2.year <= int(NOW.strftime("%Y")):
        meses.append(mes_numero_a_letras(fecha_2.month))
        datos = proceso_calculo(Modelo, proyecto, fecha_1, fecha_2, acumulado, origen)
        acumulado = datos['acumulado']
        valores.append(datos['valor'])
        fecha_1 = fecha_2 + timedelta(days=1)
        fecha_2 = obtener_fecha_fin_de_mes(fecha_1.year, fecha_1.month)
    return {'meses': json.dumps(meses), 'valores': valores}


def calculo_quincenal(proyecto, Modelo, origen):
    valores = []
    quincenas = []

    fecha_1 = proyecto.fecha_inicio
    fecha_2 = add_fortnight(fecha_1, 1)
    acumulado = 0
    contador = 0
    while fecha_2.month <= int(NOW.strftime("%m")) and fecha_2.year <= int(NOW.strftime("%Y")):
        contador += 1
        quincenas.append("Quinc {0}".format(contador))
        datos = proceso_calculo(Modelo, proyecto, fecha_1, fecha_2, acumulado, origen)
        acumulado = datos['acumulado']
        valores.append(datos['valor'])
        fecha_1 = fecha_2 + timedelta(days=1)
        fecha_2 = add_fortnight(fecha_1, 1)
    return {'quincenas': json.dumps(quincenas), 'valores': valores}


def calculo_semanal(proyecto, Modelo, origen):
    valores = []
    semanas = []

    fecha_1 = proyecto.fecha_inicio
    fecha_2 = add_week(fecha_1, 1)
    acumulado = 0
    contador = 0
    while fecha_2.month <= int(NOW.strftime("%m")) and fecha_2.year <= int(NOW.strftime("%Y")):
        contador += 1
        semanas.append("Sem {0}".format(contador))
        datos = proceso_calculo(Modelo, proyecto, fecha_1, fecha_2, acumulado, origen)
        acumulado = datos['acumulado']
        valores.append(datos['valor'])
        fecha_1 = fecha_2 + timedelta(days=1)
        fecha_2 = add_week(fecha_1, 1)
    return {'semanas': json.dumps(semanas), 'valores': valores}

Proyectos/views/novedades.py
import datetime

from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse

from Administracion.models.models import TipoNovedad
from Proyectos.models import Proyecto, ProyectoBeneficiario
from Proyectos.models.models import ProyectoNovedad, ProyectoNovedadBeneficiario
from SIGPA.views.index import AuthAbsView


class NovedadesView(AuthAbsView):
    def get(self, request):
        novedades = ProyectoNovedad.objects.all()
        return render(request, 'Proyectos/Novedades/index.html',
                      {'novedades': novedades, 'menu_actual': ['GP', 'NOVEDADES']})


class NovedadesCrearView(AuthAbsView):
    def get(self, request, id):
        proyecto = Proyecto.objects.get(id=id)
        tipos_novedades = TipoNovedad.objects.all()
        porcentajes = [{'id': 10, 'nombre': '10%'}, {'id': 20, 'nombre': '20%'}, {'id': 30, 'nombre': '30%'},
                       {'id': 50, 'nombre': '50%'}]
        beneficiarios = ProyectoBeneficiario.objects.filter(proyecto=proyecto)
        return render(request, 'Proyectos/Novedades/_modal_crear_editar.html',
                      {'proyecto': proyecto, 'beneficiarios': beneficiarios, 'porcentajes': porcentajes,
                       'tipos_novedades': tipos_novedades})

    def post(self, request, id):
        novedad = ProyectoNovedad()
        novedad.proyecto_id = id
        novedad.usuario_crea = request.user
        novedad.tipo_novedad_id = request.POST.get('tipo_novedad', '')
        novedad.responsable = request.POST.get('responsable', '')
        novedad.porcentaje = request.POST.get('porcentaje', '')
        novedad.fecha = request.POST.get('fecha_novedad', '')
        novedad.descripcion = request.POST.get('descripcion', '')
        novedad.fecha_crea = datetime.datetime.now()
        novedad.estado = True

        try:
            novedad.full_clean()
        except Exception as e:
            messages.error(request, 'Se ha generado el error: {0}'.format(e))
            return redirect(reverse('Proyectos:novedades-index'))

        novedad.save()

        benefiarios = request.POST.getlist('beneficiario[]', [])
        for ben in benefiarios:
            ProyectoNovedadBeneficiario.objects.create(beneficiario_id=ben, proyecto_novedad=novedad)

        messages.success(request, 'Se guardó la novedad correctamente.')
        return redirect(reverse('Proyectos:novedades-index'))


class NovedadesModalDetalleView(AuthAbsView):
    def get(self, request, id):
        novedad = ProyectoNovedad.objects.get(id=id)
        beneficiarios = ProyectoNovedadBeneficiario.objects.filter(proyecto_novedad=novedad)
        return render(request, 'Proyectos/Novedades/_modal_detalle.html',
                      {'novedad': novedad, 'beneficiarios': beneficiarios, })

Proyectos/templates/Proyectos/Novedades/_modal_crear_editar.html
{% load static %}
<link href="{% static 'SIGPA/Plantilla/plugins/select2/css/select2.min.css' %}" rel="stylesheet">
<form action="{% url 'proyectos:novedades-crear' proyecto.id %}" id="frm-entrega" method="post" enctype="multipart/form-data">
{% csrf_token %}
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Agregar Novedad</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group row">
                    <div class="col-xs-12 col-sm-12 mb-12">
                        <label for="select_tipo_novedad_id" id="label_tipo_novedad_id">Tipo de Novedad</label>
                        <select class="form-control form-control-md select2" id="select_tipo_novedad_id" name="tipo_novedad" required>
                            <option value="">Seleccione una opción</option>
                            {% for tn in tipos_novedades %}
                                <option value="{{ tn.id }}">{{ tn.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-xs-12 col-sm-12 mb-12">
                        <label for="select_beneficiario_id" id="label_beneficiario_id">Beneficiarios</label>
                        <select class="form-control form-control-md select2" id="select_beneficiario_id" name="beneficiario[]" multiple="multiple" required>
                            <option value="">Seleccione una opción</option>
                            {% for ben in beneficiarios %}
                                <option value="{{ ben.beneficiario_id }}">{{ ben.beneficiario.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-xs-12 col-sm-12 mb-12">
                        <label for="select_porcentaje_id" id="label_porcentaje_id">Porcentaje de Avance</label>
                        <select class="form-control form-control-md select2" id="select_porcentaje_id" name="porcentaje" required>
                            <option value="">Seleccione una opción</option>
                            {% for por in porcentajes %}
                                <option value="{{ por.id }}">{{ por.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-sm-12 mb-6 mb-sm-6">
                        <label for="fecha_novedad_id" id="label_fecha_novedad_id">Fecha de la Novedad</label>
                        <input type="date" class="form-control form-control-md" id="fecha_novedad_id" name="fecha_novedad"
                            placeholder="Seleccione una Fecha" required>
                    </div>
                    <div class="col-sm-12 mb-6 mb-sm-6">
                        <label for="descripcion_proyecto_id" id="label_descripcion_proyecto_id">Descripción del Entregable</label>
                        <textarea class="form-control form-control-md" id="descripcion_proyecto_id" name="descripcion"
                                  placeholder="Ingrese una descripción" required></textarea>
                    </div>
                    <div class="col-sm-12 mb-6 mb-sm-6">
                        <label for="responsable_id" id="label_responsable_id">Responsable</label>
                        <input type="text" class="form-control form-control-md" id="responsable_id" name="responsable"
                            placeholder="Ingrese el nombre del responsable" maxlength="100" required>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">
                    Guardar
                </button>
            </div>
        </div>
    </div>
</form>
<script src="{% static 'SIGPA/Plantilla/plugins/select2/js/select2.min.js' %}" type="text/javascript"></script>
<script src="{% static 'SIGPA/Plantilla/custom/modificacionesSelect2.js' %}" type="text/javascript"></script>
<script>
    $(".select2").select2({
        dropdownParent: $('#modal-novedad'),
        placeholder: 'Seleccione una opción',
        "language": {
            noResults: function () {
              return 'No se encontraron coincidencias';
            },
            searching: function () {
              return 'Buscando…';
            },
            removeAllItems: function () {
              return 'Quitar todas los items';
            }
        },
    }).css('width', '100%').next("span").css('width', '100%');

    $(window).resize(function() {
        $('.select2').css('width', "100%");
    });
</script>

Proyectos/templates/Proyectos/Novedades/_modal_detalle.html
<div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Detalle de Entrega: {{ entrega.proyecto.codigo_proyecto }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="col-xs-12 col-sm-12 mb-12" style="word-wrap: break-word;">
                <b>Nombre del Proyecto:</b>{{ entrega.proyecto.nombre }}<br>
                <b>Descripción de la Entrega:</b>{{ entrega.descripcion }}<br>
                <b>Fecha de la Entrega:</b>{{ entrega.fecha|date:'Y-m-d' }}<br>
                <b>Entregas:</b>{% for entrg in entregas %}{{ entrg.entregable.nombre }}{% endfor %}<br>
                <b>Beneficiario:</b>{% for ben in beneficiarios %}{{ ben.beneficiario.nombre }}{% endfor %}<br>
            </div>
        </div>
        <div class="modal-footer">
        </div>
    </div>
</div>

Proyectos/templates/Proyectos/Novedades/index.html
{% extends 'SIGPA/_base_templates/base.html' %}
{% load static %}
{% load humanize %}
{% block styles %}
    <link href="{% static 'SIGPA/DataTable/jquery.dataTables.min.css' %}" rel="stylesheet">
    <link href="{% static 'SIGPA/DataTable/responsive.dataTables.min.css' %}" rel="stylesheet">
{% endblock %}
{% block main %}
 <h1 class="h3 mb-2 text-gray-800">Novedades</h1>
                <p class="mb-4">Relacion de las novedades asociadas a los proyectos de la Fundación</p>
    <div class="card shadow mb-5">
        <div class="card-body">
            <table class="table table-bordered display nowrap w-100" id="dataTable">
                <thead>
                    <tr>
                        <th>Código del Proyecto</th>
                        <th>Tipo de Novedad</th>
                        <th>Responsable</th>
                        <th>Descripción</th>
                        <th>Fecha</th>
                        <th>Creado</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for nov in novedades %}
                    <tr>
                        <th>{{ nov.proyecto.codigo_proyecto }}</th>
                        <th>{{ nov.tipo_novedad }}</th>
                        <th>{{ nov.responsable }}</th>
                        <th>{{ nov.descripcion }}</th>
                        <th>{{ nov.fecha|date:'Y-m-d' }}</th>
                        <th>{{ nov.fecha_crea|date:'Y-m-d' }}</th>
                        <th class="text-align-center">
                            <a class="fas fa-2x fa-list-alt text-decoration-none" id="editar"
                               href="javascript:gestionarModal('{% url "proyectos:novedades-detalle" nov.id %}', 'modal-detalle')" title="Detalle"></a>
                        </th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'SIGPA/DataTable/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'SIGPA/DataTable/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'SIGPA/DataTable/modificacionesDataTable.js' %}"></script>
    <script src="{% static 'Administracion/gestionModal.js' %}"></script>
    <script src="{% static 'SIGPA/Plantilla/plugins/select2/js/select2.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'SIGPA/Plantilla/custom/modificacionesSelect2.js' %}" type="text/javascript"></script>
    <script src="{% static 'SIGPA/Plantilla/custom/selectDependiente.js' %}" type="text/javascript"></script>
    <script>
        let tabla = $('#dataTable');
        tabla.dataTable({
            responsive: true,
            lengthChange: false,
            bPaginate: true,
            aaSorting: [[0, 'asc']],
            language: idiomaTabla
        });
        tabla.find("input").attr("placeholder", "Buscar");
    </script>
{% endblock %}